# Generated by Django 4.2.29 on 2026-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobrecord_validation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrecord",
            name="downstream_delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="downstream_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="downstream_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="downstream_status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
