# Generated by Django 4.2.29 on 2026-03-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_add_downstream_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrecord",
            name="interchange_control_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ISA interchange control number",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="transaction_set_control_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ST transaction set control number",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="transaction_set_index",
            field=models.IntegerField(
                default=0,
                help_text="Index of this TX set within the interchange (0-based)",
            ),
        ),
        migrations.AddField(
            model_name="jobrecord",
            name="transaction_sets_in_interchange",
            field=models.IntegerField(
                default=1,
                help_text="Total number of TX sets in the original interchange",
            ),
        ),
    ]
