# Generated by Django 4.2.29 on 2026-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DSLExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_set", models.CharField(max_length=10)),
                ("intent", models.TextField()),
                ("dsl_source", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "maps_dsl_example",
            },
        ),
        migrations.CreateModel(
            name="DSLKeywordRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent", models.TextField()),
                ("description", models.TextField()),
                ("transaction_set", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "maps_dsl_keyword_request",
            },
        ),
        migrations.CreateModel(
            name="JediSampleFixture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_set", models.CharField(max_length=10)),
                ("description", models.CharField(max_length=255)),
                ("sample_jedi", models.JSONField()),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "maps_jedi_sample_fixture",
            },
        ),
        migrations.CreateModel(
            name="ReferenceTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "maps_reference_table",
            },
        ),
        migrations.CreateModel(
            name="TransformMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_set", models.CharField(max_length=10)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("dsl_source", models.TextField()),
                ("compiled_jsonata", models.TextField(blank=True)),
                ("validation_result", models.JSONField(blank=True, null=True)),
                ("is_live", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "maps_transform_map",
            },
        ),
    ]
