# Generated by Django 4.2.29 on 2026-03-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("maps", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_set", models.CharField(max_length=10)),
                ("raw_edi", models.TextField()),
                ("jedi_output", models.JSONField()),
                ("system_json_output", models.JSONField()),
                ("dsl_source", models.TextField(blank=True)),
                ("content_hash", models.CharField(max_length=64, unique=True)),
                ("is_validated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trading_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mapping_examples",
                        to="partners.tradingpartner",
                    ),
                ),
            ],
            options={
                "db_table": "maps_mapping_example",
                "ordering": ["-created_at"],
            },
        ),
    ]
