# Generated by Django 4.2.29 on 2026-03-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_mappingexample"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappingexample",
            name="direction",
            field=models.CharField(
                choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                default="inbound",
                max_length=10,
            ),
        ),
    ]
