# Generated by Django 4.2.29 on 2026-03-24 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_sftp_features"),
        ("maps", "0006_seed_order_service_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformmap",
            name="custom_transform_id",
            field=models.CharField(
                blank=True,
                help_text='Engine-side custom transform ID (e.g. "cevapd-204"). When set, the engine uses a coded transform instead of DSL.',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="transformmap",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transform_maps",
                to="partners.tradingpartner",
            ),
        ),
        migrations.AlterField(
            model_name="transformmap",
            name="dsl_source",
            field=models.TextField(blank=True),
        ),
    ]
