# Generated by Django 4.2.29 on 2026-03-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_add_partner_and_custom_transform"),
    ]

    operations = [
        migrations.AddField(
            model_name="mappingexample",
            name="auto_label",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated label: {PARTNER_ID}-{TX_SET}-{N:03d}",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="mappingexample",
            name="example_label",
            field=models.CharField(
                blank=True,
                help_text='Human label e.g. "fixture-01-fbtc"',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="mappingexample",
            name="target_json",
            field=models.JSONField(
                blank=True,
                help_text="Target systemJson output (Stedi target-document.json)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transformmap",
            name="stedi_conversion_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes from conversion: fields mapped, fallbacks used, custom transform flags",
            ),
        ),
        migrations.AddField(
            model_name="transformmap",
            name="stedi_conversion_preview",
            field=models.TextField(
                blank=True, help_text="Preview of the converted DSL before publishing"
            ),
        ),
        migrations.AddField(
            model_name="transformmap",
            name="stedi_mapping_json",
            field=models.TextField(
                blank=True,
                help_text="Raw Stedi mapping.json content — uploaded to auto-generate DSL or custom transform",
            ),
        ),
        migrations.AlterField(
            model_name="mappingexample",
            name="jedi_output",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mappingexample",
            name="raw_edi",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mappingexample",
            name="system_json_output",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
