# Generated by Django 4.2.29 on 2026-03-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradingPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("partner_id", models.CharField(max_length=15, unique=True)),
                ("isa_qualifier", models.CharField(default="ZZ", max_length=2)),
                (
                    "transport",
                    models.CharField(
                        choices=[("sftp", "SFTP"), ("as2", "AS2"), ("rest", "REST")],
                        max_length=10,
                    ),
                ),
                ("sftp_host", models.CharField(blank=True, max_length=255)),
                ("sftp_user", models.CharField(blank=True, max_length=255)),
                ("sftp_password", models.CharField(blank=True, max_length=255)),
                ("sftp_inbound_dir", models.CharField(blank=True, max_length=500)),
                ("sftp_outbound_dir", models.CharField(blank=True, max_length=500)),
                ("as2_id", models.CharField(blank=True, max_length=128)),
                ("as2_url", models.CharField(blank=True, max_length=500)),
                ("as2_cert", models.TextField(blank=True)),
                ("downstream_api_url", models.CharField(blank=True, max_length=500)),
                ("downstream_api_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "partners_trading_partner",
            },
        ),
    ]
