# Generated by Django 4.2.29 on 2026-03-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_sftp_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingpartner",
            name="sftp_archive_dir",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Directory to move files after processing. Defaults to {inbound_dir}/archive if blank.",
                max_length=500,
            ),
        ),
    ]
