import { mapRegistry } from '../registry';

// 997 is auto-generated by 997-generator.ts. This seed documents the structure
// and enables the ops platform to reference the 997 schema.
mapRegistry.publish({
  id: 'seed-997-outbound',
  transactionSet: '997',
  direction: 'outbound',
  mappings: [
    { jediPath: 'ak1.ak1_element_01', systemPath: 'functionalAck.functionalIdentifierCode' },
    { jediPath: 'ak1.ak1_element_02', systemPath: 'functionalAck.groupControlNumber' },
    { jediPath: 'ak2.ak2_element_01', systemPath: 'transactionAck.0.transactionSetIdentifierCode' },
    { jediPath: 'ak2.ak2_element_02', systemPath: 'transactionAck.0.transactionSetControlNumber' },
    { jediPath: 'ak5.ak5_element_01', systemPath: 'transactionAck.0.transactionSetAcknowledgmentCode' },
    { jediPath: 'ak9.ak9_element_01', systemPath: 'functionalAck.groupAcknowledgmentCode' },
    { jediPath: 'ak9.ak9_element_02', systemPath: 'functionalAck.numberOfTransactionSetsIncluded' },
    { jediPath: 'ak9.ak9_element_03', systemPath: 'functionalAck.numberOfReceivedTransactionSets' },
    { jediPath: 'ak9.ak9_element_04', systemPath: 'functionalAck.numberOfAcceptedTransactionSets' },
  ],
});
